import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getAuthUser, requireRole } from '@/lib/auth'
import { sendMail } from '@/lib/email'

export const maxDuration = 60

/**
 * Generic "email this report to directors" endpoint.
 * Body: { subject, title, rows: Record<string, unknown>[] }
 * Emails all active DIRECTOR users with CSV + PDF attachments and an HTML table.
 */
export async function POST(req: NextRequest) {
  const user = getAuthUser(req)
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  if (!requireRole(user, ['ACCOUNTANT', 'ADMIN', 'MANAGER', 'DIRECTOR'])) {
    return NextResponse.json({ error: 'Not permitted' }, { status: 403 })
  }

  const body = await req.json().catch(() => ({}))
  const title: string = body.title || 'Report'
  const subject: string = body.subject || title
  const rows: Record<string, unknown>[] = Array.isArray(body.rows) ? body.rows : []
  if (!rows.length) return NextResponse.json({ error: 'No data to email' }, { status: 400 })

  const directors = await prisma.user.findMany({ where: { role: 'DIRECTOR', isActive: true }, select: { email: true } })
  const recipients = directors.map((d) => d.email).filter(Boolean)
  if (!recipients.length) return NextResponse.json({ error: 'No director email addresses found. Add directors as users first.' }, { status: 400 })

  const keys = Object.keys(rows[0])
  const csv = [keys.join(','), ...rows.map((r) => keys.map((k) => `"${r[k] ?? ''}"`).join(','))].join('\n')

  let pdf: Buffer | null = null
  try {
    const { jsPDF } = await import('jspdf')
    const autoTable = (await import('jspdf-autotable')).default
    const doc = new jsPDF({ orientation: keys.length > 6 ? 'landscape' : 'portrait' })
    doc.setFontSize(14); doc.text(title, 14, 16)
    doc.setFontSize(9); doc.text(`Generated ${new Date().toLocaleString()}`, 14, 22)
    autoTable(doc, { startY: 26, head: [keys], body: rows.map((r) => keys.map((k) => String(r[k] ?? ''))), styles: { fontSize: 7 }, headStyles: { fillColor: [79, 70, 229] } })
    pdf = Buffer.from(doc.output('arraybuffer'))
  } catch {
    pdf = null
  }

  const rowsHtml = rows.map((r) => `<tr>${keys.map((k) => `<td style="padding:6px 8px;border-bottom:1px solid #eee">${r[k] ?? ''}</td>`).join('')}</tr>`).join('')
  const html = `
  <div style="font-family:Arial,sans-serif;max-width:760px;margin:auto;color:#222">
    <h2 style="color:#4f46e5">${title}</h2>
    <p style="color:#888;font-size:12px">Generated ${new Date().toLocaleString()}</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px">
      <thead><tr style="background:#f9fafb;text-align:left">${keys.map((k) => `<th style="padding:6px 8px">${k}</th>`).join('')}</tr></thead>
      <tbody>${rowsHtml}</tbody>
    </table>
    <p style="color:#888;font-size:12px;margin-top:16px">Generated by the Cashier Sales Management System. CSV/PDF attached.</p>
  </div>`

  const attachments: { filename: string; content: Buffer | string; contentType?: string }[] = [
    { filename: `${title.replace(/\s+/g, '-').toLowerCase()}.csv`, content: csv, contentType: 'text/csv' },
  ]
  if (pdf) attachments.push({ filename: `${title.replace(/\s+/g, '-').toLowerCase()}.pdf`, content: pdf, contentType: 'application/pdf' })

  try {
    const result = await sendMail({ to: recipients, subject, html, attachments })
    await prisma.auditLog.create({ data: { userId: user.userId, action: 'EMAIL_REPORT', entity: 'Report', details: `${title} emailed to ${recipients.join(', ')} via ${result.mode}` } })
    return NextResponse.json({ ok: true, mode: result.mode, recipients, previewUrl: result.previewUrl })
  } catch (err: unknown) {
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Failed to send email' }, { status: 500 })
  }
}
