import { prisma } from '@/lib/prisma'
import { sendMail } from '@/lib/email'
import { computePayrollReport, PayrollRow } from '@/lib/payroll'

function fmt(n: number) {
  return 'TSh ' + new Intl.NumberFormat('en-TZ', { maximumFractionDigits: 0 }).format(n)
}

async function buildPdf(periodLabel: string, rows: PayrollRow[], total: number): Promise<Buffer | null> {
  try {
    const { jsPDF } = await import('jspdf')
    const autoTable = (await import('jspdf-autotable')).default
    const doc = new jsPDF()
    doc.setFontSize(16)
    doc.text('Payroll Deduction Report', 14, 18)
    doc.setFontSize(10)
    doc.text(`Period: ${periodLabel}`, 14, 25)
    doc.text(`Total Deduction: ${fmt(total)}`, 14, 31)
    autoTable(doc, {
      startY: 37,
      head: [['Name', 'Category', 'Credit Limit', 'Amount Spent', 'Deduction']],
      body: rows.map((r) => [r.personName, r.category, fmt(r.creditLimit), fmt(r.spent), fmt(r.deduction)]),
      foot: [['', '', '', 'TOTAL', fmt(total)]],
      styles: { fontSize: 9 },
      headStyles: { fillColor: [79, 70, 229] },
    })
    return Buffer.from(doc.output('arraybuffer'))
  } catch {
    return null // PDF best-effort; email still sends with CSV
  }
}

function buildCsv(rows: PayrollRow[]): string {
  const header = ['Name', 'Category', 'Credit Limit', 'Amount Spent', 'Payroll Deduction']
  const lines = rows.map((r) => [r.personName, r.category, r.creditLimit, r.spent, r.deduction].map((v) => `"${v}"`).join(','))
  return [header.join(','), ...lines].join('\n')
}

function buildHtml(periodLabel: string, rows: PayrollRow[], totals: { total: number; overLimit: number; staffLoss: number }): string {
  const rowsHtml = rows.length
    ? rows.map((r) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #eee">${r.personName}</td>
        <td style="padding:8px;border-bottom:1px solid #eee">${r.category}</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${fmt(r.creditLimit)}</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${fmt(r.spent)}</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;color:#dc2626;font-weight:bold">${fmt(r.deduction)}</td>
      </tr>`).join('')
    : `<tr><td colspan="5" style="padding:16px;text-align:center;color:#888">No payroll deductions for this period.</td></tr>`

  return `
  <div style="font-family:Arial,sans-serif;max-width:680px;margin:auto;color:#222">
    <h2 style="color:#4f46e5">Payroll Deduction Report</h2>
    <p style="color:#555">Period: <strong>${periodLabel}</strong></p>
    <div style="display:flex;gap:12px;margin:16px 0">
      <div style="flex:1;background:#eef2ff;border-radius:8px;padding:12px">
        <div style="font-size:12px;color:#666">Total Deduction</div>
        <div style="font-size:20px;font-weight:bold;color:#4f46e5">${fmt(totals.total)}</div>
      </div>
      <div style="flex:1;background:#fff7ed;border-radius:8px;padding:12px">
        <div style="font-size:12px;color:#666">Over-Limit (Admin+Director)</div>
        <div style="font-size:20px;font-weight:bold;color:#ea580c">${fmt(totals.overLimit)}</div>
      </div>
      <div style="flex:1;background:#fef2f2;border-radius:8px;padding:12px">
        <div style="font-size:12px;color:#666">Staff Losses</div>
        <div style="font-size:20px;font-weight:bold;color:#dc2626">${fmt(totals.staffLoss)}</div>
      </div>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:14px">
      <thead>
        <tr style="background:#f9fafb;text-align:left">
          <th style="padding:8px">Name</th><th style="padding:8px">Category</th>
          <th style="padding:8px;text-align:right">Credit Limit</th>
          <th style="padding:8px;text-align:right">Amount Spent</th>
          <th style="padding:8px;text-align:right">Deduction</th>
        </tr>
      </thead>
      <tbody>${rowsHtml}</tbody>
    </table>
    <p style="color:#888;font-size:12px;margin-top:16px">Generated by the Cashier Sales Management System. CSV/PDF attached.</p>
  </div>`
}

/**
 * Computes the payroll report for a period and emails it to the given recipients
 * (or all active Directors if none provided). Shared by the manual email API
 * route and the scheduled monthly job.
 */
export async function sendPayrollReport(opts: {
  month?: string | null
  outletId?: string | null
  recipients?: string[]
}) {
  const report = await computePayrollReport({ month: opts.month, outletId: opts.outletId })
  const rows = report.rows
  const totals = report.totals

  let recipients = opts.recipients
  if (!recipients || recipients.length === 0) {
    const directors = await prisma.user.findMany({
      where: { role: 'DIRECTOR', isActive: true },
      select: { email: true },
    })
    recipients = directors.map((d) => d.email).filter(Boolean)
  }
  if (!recipients.length) {
    throw new Error('No director email addresses found. Add directors as users first.')
  }

  const month = opts.month && opts.month !== 'all' ? opts.month : 'all'
  const periodLabel = month === 'all' ? 'All Time (Outstanding)' : month
  const html = buildHtml(periodLabel, rows, totals)
  const csv = buildCsv(rows)
  const pdf = await buildPdf(periodLabel, rows, totals.total)

  const attachments: { filename: string; content: Buffer | string; contentType?: string }[] = [
    { filename: `payroll-deductions-${month}.csv`, content: csv, contentType: 'text/csv' },
  ]
  if (pdf) attachments.push({ filename: `payroll-deductions-${month}.pdf`, content: pdf, contentType: 'application/pdf' })

  const result = await sendMail({
    to: recipients,
    subject: `Payroll Deduction Report — ${periodLabel} (${fmt(totals.total)})`,
    html,
    attachments,
  })

  return { mode: result.mode, recipients, previewUrl: result.previewUrl, hasPdf: !!pdf, total: totals.total }
}
